services:
    mysqldb:
      container_name: mysqldb
      image: bharath0803/php:db-v1
      ports:
        - "3306:3306"

    application:
      container_name: mycont
      image: bharath0803/php:app-v1
      ports:
        - "1212:80"
      depends_on:
        - mysqldb
